stages:
  - build
  - deploy
  
variables:
  GIT_DEPTH: "1"

build:
  stage: build
  dependencies: []
  tags:
    - linux
  image: mono
  script:
    - sed -i '/download.mono-project.com/d' /etc/apt/sources.list /etc/apt/sources.list.d/*
    - apt update && apt -y install p7zip-full
    - msbuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.6
    - mv -f bin/Release WindBot
    - rm -rf WindBot/WindBot.exe.config
    - mv -f BotWrapper/bin/Release/Bot.exe .
    - mv -f BotWrapper/bin/Release/bot.conf .
    - mkdir dist
    - 7z a -mx9 dist/WindBot.7z WindBot Bot.exe bot.conf
  artifacts:
    paths:
      - dist/

upload_to_minio:
  stage: deploy
  dependencies:
    - build
  tags: 
    - linux
  image: python
  script:
    - pip install -U -i https://mirrors.aliyun.com/pypi/simple/ awscli
    - aws s3 --endpoint=https://minio.mycard.moe:9000 sync dist/ s3://mycard/windbot
  only:
    - tags
